# Generated by Django 4.2.3 on 2023-08-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='Roles',
        ),
    ]
