# Generated by Django 4.2.3 on 2023-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_roles_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Roles',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=9),
        ),
    ]
