version: '3'

services:
  backend:
    build: .
    container_name: social_backend
    volumes:
      - .:/social_backend
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - pgdb
      
  pgdb:
    image: postgres
    restart: always
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - ./.env

  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3.11-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - ./.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery:
    image: celery:latest
    restart: always
    build:
      context: .
    command: celery -A social_backend worker -l info
    volumes:
      - .:/social_backend
    env_file:
      - ./.env
    depends_on:
      - backend
      - rabbitmq

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  pgdbdata: null
  rabbitmq_data:

networks:
  default:
    external:
      name: main_network