version: '3'

services:
  backend:
    build: .
    container_name: project_backend
    volumes:
      - .:/project_backend
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - pgdb
      
  pgdb:
    image: postgres
    restart: always
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdbdata: null