# Generated by Django 4.2.3 on 2023-08-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_comment_alter_page_name_post_like_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='page',
        ),
        migrations.RemoveField(
            model_name='like',
            name='page',
        ),
        migrations.AddField(
            model_name='dislike',
            name='author',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='page.page', to_field='name'),
        ),
        migrations.AddField(
            model_name='like',
            name='author',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='page.page', to_field='name'),
        ),
    ]
